version: '3.1'

services:
  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - "./tmp/pgdata:/var/lib/postgresql/data"

  mongo:
    image: mongo:4.0.1
    ports:
      - "27017:27017"
    volumes:
      - "./tmp/mongodata:/data/db"
